batch_size: 16
env: CartPole-v0
episode_length: 200
eps_end: 0.01
eps_last_frame: 1000
eps_start: 1.0
gamma: 0.99
learning_rate: 0.01
replay_size: 1000
sync_rate: 10
warm_start_size: 1000
warm_start_steps: 1000
